import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const URIJOLO = "http://localhost:9000/challenge"

export default function Home() {
  const [data, setData] = useState([])

  useEffect(() => {
    console.log(data)
  }, [data])

  const challenge = async () => {
    try {
    console.log('Nuevo challenge')
    await axios.get(URIJOLO).then(res => {
      console.log("holaaa")
      setData(res.data)
      console.log(res.data)
    })
  } catch (error) {
    console.log(error)
  }
}
// CREATE TABLE challenge(
//   column1 A 
//   column2 B
// )

// CREATE TABLE conectado(
//   column1 A 
//   column2 B
// )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={challenge}>Nuevo challenge</button>
    </>
  )
}
